name: Development workflow
run-name: Development workflow
on: [push]

jobs:
  unit-tests:
    runs-on: self-hosted
    container:
      image: python:3.12-rc-bullseye
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install pip requirements
      run: |
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python3 -m pytest -v
  deploy-to-dev:
    runs-on: self-hosted
    needs: [unit-tests]
    steps:
    - name: View config
      uses: actions-hub/kubectl@v1.27.3
      env:
        KUBE_HOST: ${{ secrets.KUBE_HOST }}
        KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      with:
        args: config view --raw
