name: Development workflow
run-name: Development workflow
on: [push]

jobs:
  unit-tests:
    runs-on: self-hosted
    container:
      image: python:3.12-rc-bullseye
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install pip requirements
      run: |
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python3 -m pytest -v
  deploy-to-dev:
    runs-on: self-hosted
    needs: [unit-tests]
    container:
      image: bitnami/kubectl:1.27.3
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Check if kube-apiserver is reachable
      run: |
        curl -k http://localhost:45457/
