name: Development workflow
run-name: Development workflow
on: [push]

jobs:
  unit-tests:
    runs-on: self-hosted
    container:
      image: python:3.12-rc-bullseye
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install pip requirements
      run: |
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python3 -m pytest -v
  deploy-to-dev:
    runs-on: self-hosted
    needs: [unit-tests]
    container:
      image: ubuntu:22.04
    steps:
    - name: Install dependencies and get deployments
      env:
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      run: |
        apt-get update && apt-get install -y wget
        wget -qO "/usr/local/bin/kubectl" https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl
        chmod +x "/usr/local/bin/kubectl"
        kubectl config set-cluster kind-actions-kind --server=https://172.17.0.1:6443/ --insecure-skip-tls-verify=true
        kubectl config set-credentials actions-dev --token="${KUBE_TOKEN}"
        kubectl config set-context actions-dev --user=actions-dev --cluster=kind-actions-kind --namespace=dev
        kubectl config use-context actions-dev
        kubectl view config
        kubectl get deploy
